### PR TITLE
remove of top level administrative types

### PR DESCRIPTION
**Pull request by bszady**
I removed top-level administrative unit types composed of only one individual. The most problematic was the case of the Holy See, which I removed as type and instead of that, I have created an individual: the Holy See (Stolica Apostolska) (administrative_system_50). If my proposals are accepted I will add or introduce correct relationships between individuals by adding the "forms part of" property.

### CODE REVIEW

**Review by mereolog — CHANGES_REQUESTED** [review]
This ontology is inconsistent:

```
ERROR  14:46:58  An error occurred during reasoning: Cannot do reasoning with inconsistent ontologies!
Reason for inconsistency: Literal value "313-01-01"^^date is not valid for the rdatatype date.
```

**Comment by bszady** [comment]
done with date correction

**Review by mereolog — APPROVED** [review]
It is close to impossible to properly evaluate the changes because of the hug delta.
For future pull requests, I would recommend using https://github.com/edmcouncil/rdf-toolkit.

**Comment by bszady** [comment]
Thank you very much. I do not expect such significant changes any more.

**Pull request merged**
